package xu.test.moduledemo.sqlitedb.daotools;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import xu.test.moduledemo.sqlitedb.bean.Btn;
import xu.test.moduledemo.sqlitedb.bean.Customer;
import xu.test.moduledemo.sqlitedb.bean.Product;
import xu.test.moduledemo.sqlitedb.bean.Unique;

import xu.test.moduledemo.sqlitedb.daotools.BtnDao;
import xu.test.moduledemo.sqlitedb.daotools.CustomerDao;
import xu.test.moduledemo.sqlitedb.daotools.ProductDao;
import xu.test.moduledemo.sqlitedb.daotools.UniqueDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig btnDaoConfig;
    private final DaoConfig customerDaoConfig;
    private final DaoConfig productDaoConfig;
    private final DaoConfig uniqueDaoConfig;

    private final BtnDao btnDao;
    private final CustomerDao customerDao;
    private final ProductDao productDao;
    private final UniqueDao uniqueDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        btnDaoConfig = daoConfigMap.get(BtnDao.class).clone();
        btnDaoConfig.initIdentityScope(type);

        customerDaoConfig = daoConfigMap.get(CustomerDao.class).clone();
        customerDaoConfig.initIdentityScope(type);

        productDaoConfig = daoConfigMap.get(ProductDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        uniqueDaoConfig = daoConfigMap.get(UniqueDao.class).clone();
        uniqueDaoConfig.initIdentityScope(type);

        btnDao = new BtnDao(btnDaoConfig, this);
        customerDao = new CustomerDao(customerDaoConfig, this);
        productDao = new ProductDao(productDaoConfig, this);
        uniqueDao = new UniqueDao(uniqueDaoConfig, this);

        registerDao(Btn.class, btnDao);
        registerDao(Customer.class, customerDao);
        registerDao(Product.class, productDao);
        registerDao(Unique.class, uniqueDao);
    }
    
    public void clear() {
        btnDaoConfig.clearIdentityScope();
        customerDaoConfig.clearIdentityScope();
        productDaoConfig.clearIdentityScope();
        uniqueDaoConfig.clearIdentityScope();
    }

    public BtnDao getBtnDao() {
        return btnDao;
    }

    public CustomerDao getCustomerDao() {
        return customerDao;
    }

    public ProductDao getProductDao() {
        return productDao;
    }

    public UniqueDao getUniqueDao() {
        return uniqueDao;
    }

}
